name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      # Step 1: Checkout the source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java 17)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven  # Cache Maven dependencies

      # Step 3: Build, unit tests, and integration tests using Maven
      - name: Build, unit tests and integration tests
        run: mvn clean install

      # Step 4: Code vulnerability scanning using Grype (Anchore)
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high

      # Step 5: Upload vulnerability report in SARIF format
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
